/*
===============================================================================
05 Magnitude Analysis
===============================================================================
Purpose:
    - To measure the size of the business across different dimensions.
    - To understand the distribution of customers, products, revenue, and
      sold quantity.
    - To compare business performance across different groups.

Analysis Includes:
    - Customers by country
    - Customers by gender
    - Products by category
    - Average cost by category
    - Revenue by category
    - Revenue by customer
    - Sold quantity by country

SQL Functions Used:
    - SUM()
    - COUNT()
    - AVG()
    - GROUP BY
    - ORDER BY
    - LEFT JOIN

===============================================================================
*/

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
